# This is a basic workflow to help you get started with Actions

name: ReadVars

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  display-variables:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Do I need to "set the evironment"? Is this where it must happen?
    environment: TEST
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Use variables
        run: |
          echo "repository variable : ${{ vars.REPOSITORY_VAR }}"
          echo "organization variable : $ORGANIZATION_VAR"
          echo "overridden variable : $OVERRIDE_VAR"
          echo "variable from shell environment : $env_var"
        env:
          # REPOSITORY_VAR: ${{ vars.REPOSITORY_VAR }}
          ORGANIZATION_VAR: ${{ vars.ORGANIZATION_VAR }}
          OVERRIDE_VAR: localSetVar
        
#      - name: ${{ vars.HELLO_WORLD_STEP }}
#        if: ${{ vars.HELLO_WORLD_ENABLED == 'true' }}
#        uses: actions/hello-world-javascript-action@main
#        with:
#          who-to-greet: ${{ vars.GREET_NAME }}

